### ISSUE TITLE
Icons for Gulfstreams

### ISSUE THREAD

**Issue by Toby2you** [VATSIM-Radar/vatsim-radar#503] opened 2024-11-19 19:08 UTC
### Your Vatsim CID

1353265

### What aircraft icon(s) do you suggest to add

Icons for the Gulfstream G550 **GLF5**, and Gulfstream G650, **GLF6**, frequently used on VATSIM by X-Plane users. Example below is what it would look like for **GLF6**.
![GLF6icon](https://github.com/user-attachments/assets/9f3d0ab4-5c63-4c03-9bc0-9ea340df28e3)

### Model matching

ICAO name GLF5 and GLF6 respectively.

### Improve existing matching

There was an icon for GLF5 in Simaware.

### Validation

- [X] I have searched for other requests and didn't found any alike

**Comment by Toby2you** [comment] 2024-11-19 19:29
### **GLF6 blueprint**
![gulfstream_g650-81137](https://github.com/user-attachments/assets/53e9b54e-6731-4884-9ed7-1a6424a27457)

### **GLF5 blueprint**
![gulfstream_g550-81135](https://github.com/user-attachments/assets/8bb13aca-841a-4f40-a915-a9c011b9aead)

**Comment by DotWallop** [comment] 2024-11-26 16:13
Duplicate of #341

**Comment by DotWallop** [comment] 2024-11-26 16:14
These will be added along with several other business jets in one of the next updates!

**Closed by DotWallop** 2024-11-26 16:14 UTC
Labels: aircraft icon
