### ISSUE TITLE
Hide ATC & Layers Toggles Should be Inverted

### ISSUE THREAD

**Issue by RemoteCTO** [VATSIM-Radar/vatsim-radar#440] opened 2024-10-28 11:00 UTC
### Your Vatsim CID

1715670

### What do you suggest?

The flow of turn ON to hide items, feels slightly confusing and counterintuitive. It would make more sense for these to be flipped to ON for items that are shown (and therefore they're all on by default).

This way you are then switching various page elements *off* with the toggle.

<img width="466" alt="Screenshot 2024-10-28 at 11 57 30" src="https://github.com/user-attachments/assets/316238f5-661e-466a-8463-22208a1d49f0">

### Why do you need that?

This change would follow common UX principles and cause less confusion for users.

### Alternatives

N/A

### Additional info

N/A

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com

**Comment by daniluk4000** [comment] 2024-10-28 21:31
Duplicate of https://github.com/VATSIM-Radar/vatsim-radar/issues/433

**Closed by daniluk4000** 2024-10-28 21:31 UTC
Labels: enhancement, pending triage, next
